language: c
notifications:
  slack:
    secure: l1V62joD90cOBX0esT4C/wrY6OtFxJ9zGJA2gd9AEpzs+GDHpoSKEitKx0O9+A9+kExp9SX8yn4TdMihoVyAI4qagdeOhP7z+vL9nZOh04hy834aD3CIA/mxe8f6XhcG2S+/pyM1lNdJk97RIHtYTpMEPT7aGlLeCh/T0z+t6o1afyb0sdiAg6HqWTUlYLdMHxCRdLIBGTbZvkfCfaANV4CCp3LLHhDM5CYgidgxH8RHw9maWeUisPho9fQlTa85Eh4U51cbpybZgljba4DWmt7spBAALHR53I4qozgX/Pg1+nkJPAMKS1h8nX/Kz8un2p7McdS0mtXJIugCL6H5rEfaWNMAr9cocEIHBgEzg7/W6KJ8JZiTnlrisWZWhGqLRWGUEVFLzcK36E1w5uNdciQs/dEDGdEdLEyD11phjYWGABtZ3MkxJbNdEEfMs/6XIodSKg+TPJZT+64cAPiLB2tCn/mp3FIKnvcM0nuyVnXQfimLC2SsCJ0Q94Ys0CmgN5FbEPrMqZv8iSfhwV3T0ScMPABMRA0jeyuWXeDCHut6194RgvEH22SNQEbEFWtmr9XIIeQbQ7gh6YdDl9MrrjzWn8ZNba0RplVcq5j/Lalch+jBTFvOQETakj6r2kkpbSz09wHquFdXYb/JeCXqQdvEUXequVyq1uzkgbUjKxs=
before_install:
  - pip install --user cpp-coveralls
jobs:
  include:
    -
      script: ruby beacon/rbtools/travis/hide_jni.rb && ruby beacon/rbtools/travis/hide_test.rb && cd ./beacon/src && make db && cd ../bin && ./a.out --test
after_success:
 - coveralls -r beacon/src --gcov beacon/gcov -n $COVERALLS_TOKEN
env:
  global:
    secure: I4AIjxJ7HDu/2SpBzpF+Pq4YGrbKdFeu02BHkx6WI+sjWAqZJbR/KXxvS51C6xM8AW1lsFxWS9Qy5CRVLgWdDZhCoDaC0t2d7lkW0SldGRdMQ0Nf1UWo0ORL8kn187y4rxAW37sUKKiEjrNt/2/WofaTFSLfEhwmJmLk6NAcKHlf4j58MYulsDuzJJX0oJB3ebJtwiRbAby33Amq8qLhD1hGMdZxBM+EUggFXOTF0sTWVbWAjQZv8kDi7meEPKKgDHkIJug4QN6uPLYoHMEYJb9+1tknBEaQqp5CyiMAl+u8/Adf0PeJTuAm1FYMheoCORWg708chzEIkkIrOlUPIY+MSOYbt07gpkw3RvZlE6OLrSEB0K4w3QrJYKJb9TghZpfb3LuVyZP83viIIa9kUxqR4n6bm6N9VMf/GS38ZvQxifjb5bDINAkeyc7K12+IECMBufneBscpyoQcKD9wETX0GsU1dQ9rAxCfjHb2DY0u34oaj12FpANXT/3EY+SZd64FjOt76BBpsBSUFe+l/fNIQsaNDrMxnITJHYmP+7V9B0JivG+m5DU8SeRGPNhB9B/UqZN285Ef7BtlOd4oaVdclhfFTHilEOFjkTg0LmJ26h0h/xBXazQ/5Ki45nLkqM3iGDX6nuhhDAoJ7+8d+JPBdN1v71cz3FkAXxM8ZIg=